#ifndef BRAINFLOWBOARD_GLOBAL_H
#define BRAINFLOWBOARD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BRAINFLOWBOARD_LIBRARY)
#  define BRAINFLOWBOARD_EXPORT Q_DECL_EXPORT
#else
#  define BRAINFLOWBOARD_EXPORT Q_DECL_IMPORT
#endif

#endif // BRAINFLOWBOARD_GLOBAL_H
