//=============================================================================================================
/**
 * SPDX-License-Identifier: BSD-3-Clause
 * Copyright (c) 2026 MNE-CPP Authors
 *   Christoph Dinh <christoph.dinh@mne-cpp.org>
 *
 * @file decoding_global.cpp
 * @since May 2026
 * @brief Build-stamp accessors for the DECODINGLIB shared library.
 *
 * Exposes the embedded build date, abbreviated git hash and full git
 * hash so that the @c About dialogs and version probes of the
 * applications layer can report exactly which DECODINGLIB binary they
 * are linked against. Implementation is a thin forwarder onto the
 * compile-time constants generated by @c utils/buildinfo.h.
 */

//=============================================================================================================
// INCLUDES
//=============================================================================================================

#include "decoding_global.h"

//=============================================================================================================
// DEFINES
//=============================================================================================================

const char* DECODINGLIB::buildDateTime(){ return UTILSLIB::dateTimeNow();}

//=============================================================================================================

const char* DECODINGLIB::buildHash(){ return UTILSLIB::gitHash();}

//=============================================================================================================

const char* DECODINGLIB::buildHashLong(){ return UTILSLIB::gitHashLong();}
