// Auto-generated by tools/doxy2mdx/doxy2mdx.py — do not edit by hand.
// Regenerate with `python tools/doxy2mdx/doxy2mdx.py --generate-sidebars ...`

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const apiSidebar: SidebarsConfig['apiSidebar'] = [
    'api/index',
    {
      type: 'category',
      label: "FIFFLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/fiff/fiff-stream',
        'api/fiff/fiff-raw-data',
        'api/fiff/fiff-info',
        'api/fiff/fiff-evoked',
        'api/fiff/fiff-epochs',
        'api/fiff/fiff-cov',
        'api/fiff/fiff-proj',
        'api/fiff/fiff-coord-trans',
        'api/fiff/fiff-annotations',
        'api/fiff/fiff-annotation-event-utils'
      ],
    },
    {
      type: 'category',
      label: "MNELIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/mne/mne-forward-solution',
        'api/mne/mne-inverse-operator',
        'api/mne/mne-source-space',
        'api/mne/mne-bem',
        'api/mne/mne-icp'
      ],
    },
    {
      type: 'category',
      label: "FWDLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/fwd/compute-fwd',
        'api/fwd/fwd-bem-model',
        'api/fwd/fwd-eeg-sphere-model'
      ],
    },
    {
      type: 'category',
      label: "INVLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/inv/inv-minimum-norm',
        'api/inv/inv-cmne',
        'api/inv/inv-lcmv',
        'api/inv/inv-dics',
        'api/inv/inv-rap-music',
        'api/inv/inv-trap-music',
        'api/inv/inv-dipole-fit',
        'api/inv/inv-mxne',
        'api/inv/inv-gamma-map',
        'api/inv/inv-tf-mxne',
        'api/inv/inv-hpi-fit',
        'api/inv/inv-source-estimate',
        'api/inv/inv-vector-source-estimate',
        'api/inv/inv-volume-source-estimate',
        'api/inv/inv-source-estimate-io',
        'api/inv/inv-label-time-course',
        'api/inv/inv-resolution-matrix',
        'api/inv/inv-convenience',
        'api/inv/source-morph'
      ],
    },
    {
      type: 'category',
      label: "DSPLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/dsp/filter-kernel',
        'api/dsp/fir-filter',
        'api/dsp/iir-filter',
        'api/dsp/ica',
        'api/dsp/picard-ica',
        'api/dsp/extended-infomax',
        'api/dsp/sss',
        'api/dsp/bad-channels-maxwell',
        'api/dsp/bad-channels-lof',
        'api/dsp/eog-regression',
        'api/dsp/eeg-reference',
        'api/dsp/stim-artifact',
        'api/dsp/filter-chpi',
        'api/dsp/annotate-artifact',
        'api/dsp/bridged-electrodes',
        'api/dsp/fine-calibration',
        'api/dsp/maxwell-movement-comp',
        'api/dsp/surface-laplacian',
        'api/dsp/peak-finder',
        'api/dsp/welch-psd',
        'api/dsp/multitaper-psd',
        'api/dsp/morlet-tfr',
        'api/dsp/multitaper-tfr',
        'api/dsp/resample',
        'api/dsp/xdawn',
        'api/dsp/sphara',
        'api/dsp/connectivity-aec',
        'api/dsp/simulate'
      ],
    },
    {
      type: 'category',
      label: "CONNLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/conn/connectivity',
        'api/conn/coherence',
        'api/conn/phase-locking-value',
        'api/conn/phase-lag-index',
        'api/conn/granger-causality',
        'api/conn/partial-directed-coherence',
        'api/conn/directed-transfer-function'
      ],
    },
    {
      type: 'category',
      label: "DECODINGLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/decoding/decoding-csp',
        'api/decoding/decoding-spoc',
        'api/decoding/decoding-ssd',
        'api/decoding/ml-ica-label'
      ],
    },
    {
      type: 'category',
      label: "MLLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/ml/ml-tensor',
        'api/ml/ml-model',
        'api/ml/ml-onnx-model',
        'api/ml/ml-trainer'
      ],
    },
    {
      type: 'category',
      label: "STSLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/sts/sts-cov-estimators',
        'api/sts/stats-cluster',
        'api/sts/stats-adjacency'
      ],
    },
    {
      type: 'category',
      label: "FSLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/fs/fs-surface',
        'api/fs/fs-annotation',
        'api/fs/fs-label',
        'api/fs/fs-label-utils'
      ],
    },
    {
      type: 'category',
      label: "MATHLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/math/k-means',
        'api/math/linalg',
        'api/math/simplex-algorithm',
        'api/math/warp',
        'api/math/sphere'
      ],
    },
    {
      type: 'category',
      label: "BIDSLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/bids/bids-path',
        'api/bids/bids-raw-data'
      ],
    },
    {
      type: 'category',
      label: "UTILSLIB",
      collapsible: true,
      collapsed: true,
      items: [
        'api/utils/standard-montage',
        'api/utils/report'
      ],
    }
];

export default apiSidebar;
