import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    docsSidebar: [
        'overview',
        {
            type: 'category',
            label: 'Manual',
            link: { type: 'doc', id: 'manual/intro' },
            items: [
                {
                    type: 'category',
                    label: 'Background',
                    items: [
                        'manual/workflow',
                        'manual/forward',
                        'manual/inverse',
                        'manual/ssp',
                        'manual/fiff-format',
                        'manual/sample-dataset',
                        'manual/data-conversion',
                        'manual/mna-format',
                        'manual/glossary',
                    ],
                },
                {
                    type: 'category',
                    label: 'Applications',
                    items: [
                        {
                            type: 'category',
                            label: 'MNE Scan',
                            link: { type: 'doc', id: 'manual/scan' },
                            items: [
                                'manual/scan-prerecordeddata',
                                'manual/scan-sourceloc',
                                'manual/scan-headmonitoring',
                                'manual/scan-forward',
                                'manual/scan-brainamp',
                                'manual/scan-gusbamp',
                                'manual/scan-eegosports',
                                'manual/scan-natus',
                                'manual/scan-ftbuffer',
                                'manual/scan-lsl',
                                'manual/scan-tmsi',
                                'manual/scan-interfacewithanalyze',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'MNE Analyze',
                            link: { type: 'doc', id: 'manual/analyze' },
                            items: [
                                'manual/analyze-dataloader',
                                'manual/analyze-datamanager',
                                'manual/analyze-rawdataviewer',
                                'manual/analyze-annotationmanager',
                                'manual/analyze-average',
                                'manual/analyze-filter',
                                'manual/analyze-channelselect',
                                'manual/analyze-coregistration',
                                'manual/analyze-scaling',
                                'manual/analyze-dipolefit',
                                'manual/analyze-realtime',
                            ],
                        },
                        'manual/inspect',
                        'manual/browse-raw',
                        'manual/dipole-fit',
                        'manual/analyze-studio',
                        'manual/online',
                    ],
                },
                {
                    type: 'category',
                    label: 'Command-Line Tools',
                    link: { type: 'doc', id: 'manual/tools-overview' },
                    items: [
                        {
                            type: 'category',
                            label: 'Forward Modeling',
                            items: [
                                'manual/tools-watershed-bem',
                                'manual/tools-flash-bem',
                                'manual/tools-surf2bem',
                                'manual/tools-setup-forward-model',
                                'manual/tools-setup-mri',
                                'manual/tools-forward-solution',
                                'manual/tools-make-source-space',
                                'manual/tools-make-sphere-bem',
                                'manual/tools-prepare-bem-model',
                                'manual/tools-average-forward-solutions',
                                'manual/tools-check-surface',
                                'manual/tools-fit-sphere-to-surf',
                                'manual/tools-make-scalp-surfaces',
                                'manual/tools-transform-points',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'Inverse',
                            items: [
                                'manual/tools-inverse-operator',
                                'manual/tools-compute-mne',
                                'manual/tools-compute-raw-inverse',
                                'manual/tools-dipole-fit',
                                'manual/tools-sensitivity-map',
                                'manual/tools-smooth',
                                'manual/tools-volume-data2mri',
                                'manual/tools-compute-cmne',
                                'manual/tools-inverse-pipeline',
                                'manual/tools-label-ssp',
                                'manual/tools-average-estimates',
                                'manual/tools-process-stc',
                                'manual/tools-make-uniform-stc',
                                'manual/tools-map-data',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'Preprocessing',
                            items: [
                                'manual/tools-anonymize',
                                'manual/tools-process-raw',
                                'manual/tools-mark-bad-channels',
                                'manual/tools-compensate-data',
                                'manual/tools-cov2proj',
                                'manual/tools-add-to-meas-info',
                                'manual/tools-create-comp-data',
                                'manual/tools-fix-mag-coil-types',
                                'manual/tools-insert-4d-comp',
                                'manual/tools-rename-channels',
                                'manual/tools-add-triggers',
                                'manual/tools-change-baselines',
                                'manual/tools-change-nave',
                                'manual/tools-copy-processing-history',
                                'manual/tools-fix-stim14',
                                'manual/tools-make-derivations',
                                'manual/tools-toggle-skips',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'Conversion',
                            items: [
                                'manual/tools-edf2fiff',
                                'manual/tools-brain-vision2fiff',
                                'manual/tools-ctf2fiff',
                                'manual/tools-ctf-dig2fiff',
                                'manual/tools-kit2fiff',
                                'manual/tools-raw2mat',
                                'manual/tools-eximia2fiff',
                                'manual/tools-tufts2fiff',
                                'manual/tools-convert-dig-data',
                                'manual/tools-convert-surface',
                                'manual/tools-make-cor-set',
                                'manual/tools-convert-ctf-markers',
                                'manual/tools-epochs2mat',
                                'manual/tools-mna-bids-converter',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'Surface',
                            items: [
                                'manual/tools-annot2labels',
                                'manual/tools-add-patch-info',
                                'manual/tools-volume-source-space',
                                'manual/tools-morph-labels',
                                'manual/tools-make-morph-maps',
                                'manual/tools-make-eeg-layout',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'Info',
                            items: [
                                'manual/tools-show-fiff',
                                'manual/tools-list-source-space',
                                'manual/tools-compare-fif-files',
                                'manual/tools-collect-transforms',
                                'manual/tools-list-bem',
                                'manual/tools-check-eeg-locations',
                                'manual/tools-evoked-data-summary',
                                'manual/tools-list-coil-def',
                                'manual/tools-list-proj',
                                'manual/tools-sensor-locations',
                                'manual/tools-show-mna',
                            ],
                        },
                        'manual/tools-rt-server',
                        'manual/tools-simu',
                    ],
                },
            ],
        },
        'publications',
        'cite',
    ],
    developmentSidebar: [
        {
            type: 'category',
            label: 'Build & Deploy',
            items: [
                'development/buildguide-cmake',
                {
                    type: 'category',
                    label: 'WebAssembly',
                    link: { type: 'doc', id: 'development/wasm' },
                    items: [
                        'development/wasm-buildguide',
                        'development/wasm-testing',
                    ],
                },
                {
                    type: 'category',
                    label: 'Continuous Integration',
                    link: { type: 'doc', id: 'development/ci' },
                    items: [
                        'development/ci-ghactions',
                        'development/ci-deployment',
                        'development/ci-releasecycle',
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Contributing',
            link: { type: 'doc', id: 'development/contribute' },
            items: [
                'development/contr-guide',
                'development/contr-style',
                'development/contr-git',
                'development/contr-docuimprovements',
                'development/writingtest',
            ],
        },
        {
            type: 'category',
            label: 'Library API',
            link: { type: 'doc', id: 'development/api' },
            items: [
                'development/api-fiff',
                'development/api-mne',
                'development/api-fwd',
                'development/api-dsp',
                'development/api-inverse',
                'development/api-connectivity',
                'development/api-disp3d',
                'development/api-mna',
                'development/api-ml',
                'development/api-sts',
            ],
        },
        {
            type: 'category',
            label: 'Plugin Development',
            items: [
                {
                    type: 'category',
                    label: 'MNE Scan',
                    link: { type: 'doc', id: 'development/scan' },
                    items: [
                        'development/scan-acq',
                        'development/scan-plugin',
                    ],
                },
                {
                    type: 'category',
                    label: 'MNE Analyze',
                    link: { type: 'doc', id: 'development/analyze' },
                    items: [
                        'development/analyze-plugin',
                        'development/analyze-event',
                        'development/analyze-datamodel',
                    ],
                },
            ],
        },
    ],
};

export default sidebars;
