//=============================================================================================================
/**
 * @file     test_lsl.cpp
 * @author   Christoph Dinh <chdinh@nmr.mgh.harvard.edu>
 * @since    2.0.0
 * @date     March, 2026
 *
 * @section  LICENSE
 *
 * Copyright (C) 2026, Christoph Dinh. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that
 * the following conditions are met:
 *     * Redistributions of source code must retain the above copyright notice, this list of conditions and the
 *       following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and
 *       the following disclaimer in the documentation and/or other materials provided with the distribution.
 *     * Neither the name of MNE-CPP authors nor the names of its contributors may be used
 *       to endorse or promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 *
 * @brief    Comprehensive tests for the MNE-CPP LSL library.
 *
 */

//=============================================================================================================
// INCLUDES
//=============================================================================================================

#include <lsl/lsl.h>

//=============================================================================================================
// QT INCLUDES
//=============================================================================================================

#include <QtTest/QtTest>
#include <QThread>

//=============================================================================================================
// STL INCLUDES
//=============================================================================================================

#include <cmath>
#include <algorithm>
#include <numeric>

//=============================================================================================================
// USED NAMESPACES
//=============================================================================================================

using namespace LSLLIB;

//=============================================================================================================
/**
 * @brief Comprehensive test suite for the MNE-CPP LSL library.
 *
 * Tests cover:
 *   - stream_info construction, accessors, serialization/deserialization
 *   - ChannelFormat enum class
 *   - stream_outlet / stream_inlet data flow (push/pull)
 *   - Stream discovery (resolve_streams, resolve_stream)
 *   - Edge cases and error handling
 */
class TestLsl : public QObject
{
    Q_OBJECT

private slots:

    //=========================================================================================================
    // stream_info tests
    //=========================================================================================================

    void testStreamInfoDefaultConstruction();
    void testStreamInfoParameterizedConstruction();
    void testStreamInfoCopyConstruction();
    void testStreamInfoCopyAssignment();
    void testStreamInfoAccessors();
    void testStreamInfoNetworkEndpoint();
    void testStreamInfoAutoGeneratedFields();
    void testStreamInfoUniqueUids();

    //=========================================================================================================
    // ChannelFormat tests
    //=========================================================================================================

    void testChannelFormatValues();
    void testChannelFormatDefault();

    //=========================================================================================================
    // Serialization tests
    //=========================================================================================================

    void testStreamInfoRoundTrip();
    void testStreamInfoRoundTripAllFormats();
    void testStreamInfoSerializationFormat();
    void testStreamInfoDeserializationInvalidHeader();
    void testStreamInfoDeserializationTooFewFields();
    void testStreamInfoDeserializationEmptyString();
    void testStreamInfoSpecialCharacters();
    void testStreamInfoPreservesDataPort();

    //=========================================================================================================
    // stream_outlet tests
    //=========================================================================================================

    void testStreamOutletConstruction();
    void testStreamOutletInfo();
    void testStreamOutletPortAssignment();
    void testStreamOutletNoConsumersInitially();
    void testStreamOutletPushSample();
    void testStreamOutletPushChunk();

    //=========================================================================================================
    // stream_inlet tests
    //=========================================================================================================

    void testStreamInletConstruction();
    void testStreamInletOpenInvalidHost();
    void testStreamInletPullWithoutOpen();

    //=========================================================================================================
    // End-to-end data flow tests
    //=========================================================================================================

    void testOutletInletSingleSample();
    void testOutletInletMultipleChunks();
    void testOutletInletMultiChannel();
    void testOutletInletLargeChunk();
    void testOutletMultipleInlets();

    //=========================================================================================================
    // Discovery tests
    //=========================================================================================================

    void testResolveStreamsFindsOutlet();
    void testResolveStreamByName();
    void testResolveStreamByType();
    void testResolveStreamBySourceId();
    void testResolveStreamsTimeout();
    void testResolveStreamNoMatch();
    void testResolveStreamsMultipleOutlets();

    //=========================================================================================================
    // Build info tests
    //=========================================================================================================

    void testBuildInfo();
};

//=============================================================================================================
// stream_info tests
//=============================================================================================================

void TestLsl::testStreamInfoDefaultConstruction()
{
    stream_info info;
    QVERIFY(info.name().empty());
    QVERIFY(info.type().empty());
    QCOMPARE(info.channel_count(), 0);
    QCOMPARE(info.nominal_srate(), 0.0);
    QCOMPARE(info.channel_format(), ChannelFormat::Undefined);
    QVERIFY(info.source_id().empty());
    QVERIFY(info.uid().empty());
    QVERIFY(info.hostname().empty());
    QCOMPARE(info.data_port(), 0);
    QVERIFY(info.data_host().empty());
}

//=============================================================================================================

void TestLsl::testStreamInfoParameterizedConstruction()
{
    stream_info info("TestEEG", "EEG", 32, 512.0, ChannelFormat::Float32, "dev001");
    QCOMPARE(info.name(), std::string("TestEEG"));
    QCOMPARE(info.type(), std::string("EEG"));
    QCOMPARE(info.channel_count(), 32);
    QCOMPARE(info.nominal_srate(), 512.0);
    QCOMPARE(info.channel_format(), ChannelFormat::Float32);
    QCOMPARE(info.source_id(), std::string("dev001"));
    QVERIFY(!info.uid().empty());
    QVERIFY(!info.hostname().empty());
}

//=============================================================================================================

void TestLsl::testStreamInfoCopyConstruction()
{
    stream_info original("CopyTest", "Markers", 1, 0.0, ChannelFormat::String, "src1");
    stream_info copy(original);

    QCOMPARE(copy.name(), original.name());
    QCOMPARE(copy.type(), original.type());
    QCOMPARE(copy.channel_count(), original.channel_count());
    QCOMPARE(copy.nominal_srate(), original.nominal_srate());
    QCOMPARE(copy.channel_format(), original.channel_format());
    QCOMPARE(copy.source_id(), original.source_id());
    QCOMPARE(copy.uid(), original.uid());
    QCOMPARE(copy.hostname(), original.hostname());
}

//=============================================================================================================

void TestLsl::testStreamInfoCopyAssignment()
{
    stream_info original("AssignTest", "EMG", 8, 1000.0, ChannelFormat::Int16, "emg1");
    stream_info assigned;
    assigned = original;

    QCOMPARE(assigned.name(), original.name());
    QCOMPARE(assigned.type(), original.type());
    QCOMPARE(assigned.channel_count(), original.channel_count());
    QCOMPARE(assigned.nominal_srate(), original.nominal_srate());
    QCOMPARE(assigned.channel_format(), original.channel_format());
    QCOMPARE(assigned.source_id(), original.source_id());
    QCOMPARE(assigned.uid(), original.uid());
}

//=============================================================================================================

void TestLsl::testStreamInfoAccessors()
{
    stream_info info("AccTest", "MEG", 306, 1000.0, ChannelFormat::Double64, "meg1");

    QCOMPARE(info.name(), std::string("AccTest"));
    QCOMPARE(info.type(), std::string("MEG"));
    QCOMPARE(info.channel_count(), 306);
    QCOMPARE(info.nominal_srate(), 1000.0);
    QCOMPARE(info.channel_format(), ChannelFormat::Double64);
    QCOMPARE(info.source_id(), std::string("meg1"));
}

//=============================================================================================================

void TestLsl::testStreamInfoNetworkEndpoint()
{
    stream_info info("NetTest", "EEG", 1, 100.0);

    QCOMPARE(info.data_port(), 0);
    QVERIFY(info.data_host().empty());

    info.set_data_port(12345);
    info.set_data_host("192.168.1.100");

    QCOMPARE(info.data_port(), 12345);
    QCOMPARE(info.data_host(), std::string("192.168.1.100"));
}

//=============================================================================================================

void TestLsl::testStreamInfoAutoGeneratedFields()
{
    stream_info info("AutoTest", "EEG", 1, 100.0);

    // UID should be auto-generated (UUID format)
    QVERIFY(!info.uid().empty());
    QVERIFY(info.uid().size() > 10);  // UUID is at least ~36 chars

    // Hostname should be set from local machine
    QVERIFY(!info.hostname().empty());
}

//=============================================================================================================

void TestLsl::testStreamInfoUniqueUids()
{
    stream_info info1("Stream1", "EEG", 1, 100.0);
    stream_info info2("Stream2", "EEG", 1, 100.0);

    // Different stream_info instances should have different UIDs
    QVERIFY(info1.uid() != info2.uid());
}

//=============================================================================================================
// ChannelFormat tests
//=============================================================================================================

void TestLsl::testChannelFormatValues()
{
    QCOMPARE(static_cast<int>(ChannelFormat::Undefined), 0);
    QCOMPARE(static_cast<int>(ChannelFormat::Float32), 1);
    QCOMPARE(static_cast<int>(ChannelFormat::Double64), 2);
    QCOMPARE(static_cast<int>(ChannelFormat::String), 3);
    QCOMPARE(static_cast<int>(ChannelFormat::Int32), 4);
    QCOMPARE(static_cast<int>(ChannelFormat::Int16), 5);
    QCOMPARE(static_cast<int>(ChannelFormat::Int8), 6);
    QCOMPARE(static_cast<int>(ChannelFormat::Int64), 7);
}

//=============================================================================================================

void TestLsl::testChannelFormatDefault()
{
    // Default parameter should be Float32
    stream_info info("FmtTest", "EEG", 1, 100.0);
    QCOMPARE(info.channel_format(), ChannelFormat::Float32);
}

//=============================================================================================================
// Serialization tests
//=============================================================================================================

void TestLsl::testStreamInfoRoundTrip()
{
    stream_info original("RoundTrip", "EEG", 64, 256.0, ChannelFormat::Float32, "rt_source");
    original.set_data_port(9999);

    std::string serialized = original.to_string();
    stream_info restored = stream_info::from_string(serialized);

    QCOMPARE(restored.name(), original.name());
    QCOMPARE(restored.type(), original.type());
    QCOMPARE(restored.channel_count(), original.channel_count());
    QCOMPARE(restored.nominal_srate(), original.nominal_srate());
    QCOMPARE(restored.channel_format(), original.channel_format());
    QCOMPARE(restored.source_id(), original.source_id());
    QCOMPARE(restored.uid(), original.uid());
    QCOMPARE(restored.hostname(), original.hostname());
    QCOMPARE(restored.data_port(), original.data_port());
}

//=============================================================================================================

void TestLsl::testStreamInfoRoundTripAllFormats()
{
    const ChannelFormat formats[] = {
        ChannelFormat::Undefined, ChannelFormat::Float32, ChannelFormat::Double64,
        ChannelFormat::String, ChannelFormat::Int32, ChannelFormat::Int16,
        ChannelFormat::Int8, ChannelFormat::Int64
    };

    for (auto fmt : formats) {
        stream_info original("FmtRT", "Test", 1, 100.0, fmt, "src");
        std::string s = original.to_string();
        stream_info restored = stream_info::from_string(s);
        QCOMPARE(restored.channel_format(), fmt);
    }
}

//=============================================================================================================

void TestLsl::testStreamInfoSerializationFormat()
{
    stream_info info("MyStream", "EEG", 32, 512.0, ChannelFormat::Float32, "src1");
    std::string s = info.to_string();

    // Should start with MNELSL1 header
    QVERIFY(s.substr(0, 7) == "MNELSL1");

    // Should be pipe-delimited with 10 fields
    int pipeCount = static_cast<int>(std::count(s.begin(), s.end(), '|'));
    QCOMPARE(pipeCount, 9);  // 10 fields = 9 pipes
}

//=============================================================================================================

void TestLsl::testStreamInfoDeserializationInvalidHeader()
{
    stream_info result = stream_info::from_string("INVALID|a|b|1|100|uid|host|src|0|1");
    QVERIFY(result.name().empty());
    QVERIFY(result.uid().empty());
}

//=============================================================================================================

void TestLsl::testStreamInfoDeserializationTooFewFields()
{
    stream_info result = stream_info::from_string("MNELSL1|a|b|1");
    QVERIFY(result.name().empty());
}

//=============================================================================================================

void TestLsl::testStreamInfoDeserializationEmptyString()
{
    stream_info result = stream_info::from_string("");
    QVERIFY(result.name().empty());
    QVERIFY(result.uid().empty());
    QCOMPARE(result.channel_count(), 0);
}

//=============================================================================================================

void TestLsl::testStreamInfoSpecialCharacters()
{
    // Ensure names with spaces work (but pipes would break protocol - we don't test that)
    stream_info info("My Stream Name", "EEG Data", 1, 100.0, ChannelFormat::Float32, "source 1");
    std::string s = info.to_string();
    stream_info restored = stream_info::from_string(s);

    QCOMPARE(restored.name(), std::string("My Stream Name"));
    QCOMPARE(restored.type(), std::string("EEG Data"));
    QCOMPARE(restored.source_id(), std::string("source 1"));
}

//=============================================================================================================

void TestLsl::testStreamInfoPreservesDataPort()
{
    stream_info info("PortTest", "EEG", 1, 100.0);
    info.set_data_port(54321);

    std::string s = info.to_string();
    stream_info restored = stream_info::from_string(s);

    QCOMPARE(restored.data_port(), 54321);
}

//=============================================================================================================
// stream_outlet tests
//=============================================================================================================

void TestLsl::testStreamOutletConstruction()
{
    stream_info info("OutletTest", "EEG", 4, 250.0);
    stream_outlet outlet(info);

    // Should not crash; outlet is running
    QVERIFY(true);
}

//=============================================================================================================

void TestLsl::testStreamOutletInfo()
{
    stream_info info("InfoTest", "EEG", 8, 500.0, ChannelFormat::Float32, "outlet1");
    stream_outlet outlet(info);

    stream_info outInfo = outlet.info();
    QCOMPARE(outInfo.name(), std::string("InfoTest"));
    QCOMPARE(outInfo.type(), std::string("EEG"));
    QCOMPARE(outInfo.channel_count(), 8);
    QCOMPARE(outInfo.nominal_srate(), 500.0);
}

//=============================================================================================================

void TestLsl::testStreamOutletPortAssignment()
{
    stream_info info("PortTest", "EEG", 1, 100.0);
    stream_outlet outlet(info);

    // Give the background thread a moment to start the TCP server
    QThread::msleep(100);

    stream_info outInfo = outlet.info();
    // Port should be assigned by OS (non-zero)
    QVERIFY(outInfo.data_port() > 0);
}

//=============================================================================================================

void TestLsl::testStreamOutletNoConsumersInitially()
{
    stream_info info("NoConsumerTest", "EEG", 1, 100.0);
    stream_outlet outlet(info);

    QThread::msleep(50);
    QVERIFY(!outlet.have_consumers());
}

//=============================================================================================================

void TestLsl::testStreamOutletPushSample()
{
    stream_info info("PushTest", "EEG", 3, 100.0);
    stream_outlet outlet(info);

    // Should not crash even without consumers
    std::vector<float> sample = {1.0f, 2.0f, 3.0f};
    outlet.push_sample(sample);
    QVERIFY(true);
}

//=============================================================================================================

void TestLsl::testStreamOutletPushChunk()
{
    stream_info info("ChunkTest", "EEG", 2, 100.0);
    stream_outlet outlet(info);

    std::vector<std::vector<float>> chunk = {
        {1.0f, 2.0f},
        {3.0f, 4.0f},
        {5.0f, 6.0f}
    };
    outlet.push_chunk(chunk);
    QVERIFY(true);
}

//=============================================================================================================
// stream_inlet tests
//=============================================================================================================

void TestLsl::testStreamInletConstruction()
{
    stream_info info("InletTest", "EEG", 4, 250.0);
    info.set_data_port(12345);
    info.set_data_host("127.0.0.1");

    stream_inlet inlet(info);
    QVERIFY(true);  // Should not crash
}

//=============================================================================================================

void TestLsl::testStreamInletOpenInvalidHost()
{
    stream_info info("BadHost", "EEG", 1, 100.0);
    // No host/port set — should throw
    stream_inlet inlet(info);

    bool threw = false;
    try {
        inlet.open_stream();
    } catch (const std::runtime_error&) {
        threw = true;
    }
    QVERIFY(threw);
}

//=============================================================================================================

void TestLsl::testStreamInletPullWithoutOpen()
{
    stream_info info("NoPull", "EEG", 1, 100.0);
    stream_inlet inlet(info);

    // Pull without opening should return empty
    auto chunk = inlet.pull_chunk_float();
    QVERIFY(chunk.empty());
}

//=============================================================================================================
// End-to-end data flow tests
//=============================================================================================================

void TestLsl::testOutletInletSingleSample()
{
    const int nChannels = 3;
    stream_info outInfo("E2E_Single", "EEG", nChannels, 100.0);
    stream_outlet outlet(outInfo);

    // Wait for the outlet to be ready
    QThread::msleep(200);

    // Create inlet from outlet's info
    stream_info resolvedInfo = outlet.info();
    resolvedInfo.set_data_host("127.0.0.1");

    stream_inlet inlet(resolvedInfo);
    inlet.open_stream();

    // Push a sample
    std::vector<float> sample = {1.5f, 2.5f, 3.5f};
    outlet.push_sample(sample);

    // Wait for data to arrive
    QThread::msleep(200);

    auto chunk = inlet.pull_chunk<float>();
    QVERIFY(!chunk.empty());

    // Verify the sample data
    bool found = false;
    for (const auto& s : chunk) {
        if (s.size() == static_cast<size_t>(nChannels) &&
            std::abs(s[0] - 1.5f) < 1e-6f &&
            std::abs(s[1] - 2.5f) < 1e-6f &&
            std::abs(s[2] - 3.5f) < 1e-6f) {
            found = true;
            break;
        }
    }
    QVERIFY(found);

    inlet.close_stream();
}

//=============================================================================================================

void TestLsl::testOutletInletMultipleChunks()
{
    const int nChannels = 2;
    stream_info outInfo("E2E_Multi", "EEG", nChannels, 100.0);
    stream_outlet outlet(outInfo);

    QThread::msleep(200);

    stream_info resolvedInfo = outlet.info();
    resolvedInfo.set_data_host("127.0.0.1");

    stream_inlet inlet(resolvedInfo);
    inlet.open_stream();

    // Push multiple chunks
    const int nSamples = 10;
    for (int i = 0; i < nSamples; ++i) {
        outlet.push_sample({static_cast<float>(i), static_cast<float>(i * 10)});
    }

    QThread::msleep(300);

    auto chunk = inlet.pull_chunk_float();

    // We should receive all samples (though timing may vary)
    QVERIFY(!chunk.empty());
    QVERIFY(static_cast<int>(chunk.size()) <= nSamples);

    // Verify channel count
    for (const auto& s : chunk) {
        QCOMPARE(static_cast<int>(s.size()), nChannels);
    }

    inlet.close_stream();
}

//=============================================================================================================

void TestLsl::testOutletInletMultiChannel()
{
    const int nChannels = 64;
    stream_info outInfo("E2E_ManyChannels", "EEG", nChannels, 500.0);
    stream_outlet outlet(outInfo);

    QThread::msleep(200);

    stream_info resolvedInfo = outlet.info();
    resolvedInfo.set_data_host("127.0.0.1");
    stream_inlet inlet(resolvedInfo);
    inlet.open_stream();

    // Create a sample with sequential values
    std::vector<float> sample(nChannels);
    std::iota(sample.begin(), sample.end(), 0.0f);
    outlet.push_sample(sample);

    QThread::msleep(200);

    auto chunk = inlet.pull_chunk_float();
    QVERIFY(!chunk.empty());
    QCOMPARE(static_cast<int>(chunk[0].size()), nChannels);

    // Verify data integrity
    for (int ch = 0; ch < nChannels; ++ch) {
        QVERIFY(std::abs(chunk[0][ch] - static_cast<float>(ch)) < 1e-6f);
    }

    inlet.close_stream();
}

//=============================================================================================================

void TestLsl::testOutletInletLargeChunk()
{
    const int nChannels = 4;
    const int nSamples = 500;

    stream_info outInfo("E2E_Large", "EEG", nChannels, 1000.0);
    stream_outlet outlet(outInfo);

    QThread::msleep(200);

    stream_info resolvedInfo = outlet.info();
    resolvedInfo.set_data_host("127.0.0.1");
    stream_inlet inlet(resolvedInfo);
    inlet.open_stream();

    // Push a large chunk
    std::vector<std::vector<float>> bigChunk;
    bigChunk.reserve(nSamples);
    for (int i = 0; i < nSamples; ++i) {
        bigChunk.push_back({static_cast<float>(i), static_cast<float>(i * 2),
                            static_cast<float>(i * 3), static_cast<float>(i * 4)});
    }
    outlet.push_chunk(bigChunk);

    // Allow time for all data to transfer
    QThread::msleep(500);

    // Collect all received samples
    std::vector<std::vector<float>> allReceived;
    for (int attempt = 0; attempt < 5; ++attempt) {
        auto received = inlet.pull_chunk_float();
        allReceived.insert(allReceived.end(), received.begin(), received.end());
        if (static_cast<int>(allReceived.size()) >= nSamples) break;
        QThread::msleep(100);
    }

    QVERIFY(!allReceived.empty());
    // We should receive a significant portion (network timing may affect exact count)
    QVERIFY(static_cast<int>(allReceived.size()) > nSamples / 2);

    inlet.close_stream();
}

//=============================================================================================================

void TestLsl::testOutletMultipleInlets()
{
    const int nChannels = 2;
    stream_info outInfo("E2E_MultiInlet", "EEG", nChannels, 100.0);
    stream_outlet outlet(outInfo);

    QThread::msleep(200);

    stream_info resolvedInfo = outlet.info();
    resolvedInfo.set_data_host("127.0.0.1");

    stream_inlet inlet1(resolvedInfo);
    stream_inlet inlet2(resolvedInfo);

    inlet1.open_stream();
    inlet2.open_stream();

    QThread::msleep(100);

    // Outlet should see consumers
    QVERIFY(outlet.have_consumers());

    // Push data
    outlet.push_sample({42.0f, 84.0f});

    QThread::msleep(200);

    // Both inlets should receive data
    auto chunk1 = inlet1.pull_chunk_float();
    auto chunk2 = inlet2.pull_chunk_float();

    QVERIFY(!chunk1.empty());
    QVERIFY(!chunk2.empty());

    inlet1.close_stream();
    inlet2.close_stream();
}

//=============================================================================================================
// Discovery tests
//=============================================================================================================

void TestLsl::testResolveStreamsFindsOutlet()
{
    stream_info outInfo("DiscoverMe", "EEG", 4, 250.0, ChannelFormat::Float32, "disc_src");
    stream_outlet outlet(outInfo);

    QThread::msleep(600);  // Allow at least one broadcast

    auto streams = resolve_streams(1.5);

    if (streams.empty()) {
        QSKIP("Multicast discovery not available in this environment");
    }

    // Find our stream by UID
    bool found = false;
    for (const auto& s : streams) {
        if (s.uid() == outlet.info().uid()) {
            found = true;
            QCOMPARE(s.name(), std::string("DiscoverMe"));
            QCOMPARE(s.type(), std::string("EEG"));
            QCOMPARE(s.channel_count(), 4);
            QCOMPARE(s.nominal_srate(), 250.0);
            QVERIFY(s.data_port() > 0);
            QVERIFY(!s.data_host().empty());
            break;
        }
    }
    QVERIFY(found);
}

//=============================================================================================================

void TestLsl::testResolveStreamByName()
{
    stream_info outInfo("UniqueNameXYZ", "EEG", 1, 100.0);
    stream_outlet outlet(outInfo);

    QThread::msleep(600);

    auto streams = resolve_stream("name", "UniqueNameXYZ", 1.5);

    if (streams.empty()) {
        QSKIP("Multicast discovery not available in this environment");
    }

    bool found = false;
    for (const auto& s : streams) {
        if (s.uid() == outlet.info().uid()) {
            found = true;
            break;
        }
    }
    QVERIFY(found);
}

//=============================================================================================================

void TestLsl::testResolveStreamByType()
{
    stream_info outInfo("TypeTest", "UniqueTypeABC", 1, 100.0);
    stream_outlet outlet(outInfo);

    QThread::msleep(600);

    auto streams = resolve_stream("type", "UniqueTypeABC", 1.5);

    if (streams.empty()) {
        QSKIP("Multicast discovery not available in this environment");
    }

    bool found = false;
    for (const auto& s : streams) {
        if (s.uid() == outlet.info().uid()) {
            found = true;
            break;
        }
    }
    QVERIFY(found);
}

//=============================================================================================================

void TestLsl::testResolveStreamBySourceId()
{
    stream_info outInfo("SrcIdTest", "EEG", 1, 100.0, ChannelFormat::Float32, "unique_src_42");
    stream_outlet outlet(outInfo);

    QThread::msleep(600);

    auto streams = resolve_stream("source_id", "unique_src_42", 1.5);

    if (streams.empty()) {
        QSKIP("Multicast discovery not available in this environment");
    }

    bool found = false;
    for (const auto& s : streams) {
        if (s.uid() == outlet.info().uid()) {
            found = true;
            break;
        }
    }
    QVERIFY(found);
}

//=============================================================================================================

void TestLsl::testResolveStreamsTimeout()
{
    // Short timeout with no outlets should return empty quickly
    auto start = std::chrono::steady_clock::now();
    auto streams = resolve_streams(0.1);
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
        std::chrono::steady_clock::now() - start).count();

    // Should complete within a reasonable time around the timeout
    // (some overhead is expected, but should be less than 2 seconds)
    QVERIFY(elapsed < 2000);
}

//=============================================================================================================

void TestLsl::testResolveStreamNoMatch()
{
    stream_info outInfo("NoMatchTest", "EEG", 1, 100.0);
    stream_outlet outlet(outInfo);

    QThread::msleep(600);

    // Search for a type that doesn't match
    auto streams = resolve_stream("type", "NonExistentType_XYZ_123", 1.0);

    // Should not find our stream (different type)
    bool found = false;
    for (const auto& s : streams) {
        if (s.uid() == outlet.info().uid()) {
            found = true;
        }
    }
    QVERIFY(!found);
}

//=============================================================================================================

void TestLsl::testResolveStreamsMultipleOutlets()
{
    stream_info info1("Multi1", "EEG", 1, 100.0, ChannelFormat::Float32, "m1");
    stream_info info2("Multi2", "EMG", 2, 200.0, ChannelFormat::Float32, "m2");

    stream_outlet outlet1(info1);
    stream_outlet outlet2(info2);

    QThread::msleep(600);

    auto streams = resolve_streams(1.5);

    if (streams.empty()) {
        QSKIP("Multicast discovery not available in this environment");
    }

    // Find both streams
    bool found1 = false, found2 = false;
    for (const auto& s : streams) {
        if (s.uid() == outlet1.info().uid()) found1 = true;
        if (s.uid() == outlet2.info().uid()) found2 = true;
    }
    QVERIFY(found1);
    QVERIFY(found2);
}

//=============================================================================================================
// Build info tests
//=============================================================================================================

void TestLsl::testBuildInfo()
{
    const char* dt = LSLLIB::buildDateTime();
    QVERIFY(dt != nullptr);
    QVERIFY(std::strlen(dt) > 0);

    const char* hash = LSLLIB::buildHash();
    QVERIFY(hash != nullptr);

    const char* hashLong = LSLLIB::buildHashLong();
    QVERIFY(hashLong != nullptr);
}

//=============================================================================================================

QTEST_GUILESS_MAIN(TestLsl)
#include "test_lsl.moc"
