#!/bin/bash
# set -e

VerboseMode="true"
ExitOnFirstFail="false"
CompoundOutput=0

##########

RepoRootDir="$(dirname "$BASH_SOURCE")/../.."
echo $RepoRootDir

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RepoRootDir/lib

for test in ./bin/test_*;
do
  # Run all tests and call gcov on all cpp files after each test run. Then upload to codecov for every test run.
  # Codecov is able to process multiple uploads and merge them as soon as the CI job is done.
  if [ $VerboseMode == "false" ];
  then
    $test &> /dev/null
    lastReturnValue=$?
  else
    $test 
    lastReturnValue=$?
  fi

  if [ $lastReturnValue -ne 0 ];
  then 
    CompoundOutput=$((CompoundOutput + 1))
    echo ">> Test $test FAILED!   ******** "

    if [ $ExitOnFirstFail == "true" ];
    then
      exit $lastReturnValue
    fi

  else
    echo ">> Test $test is rock solid!"
  fi
done

exit $CompoundOutput
