//=============================================================================================================
/**
 * SPDX-License-Identifier: BSD-3-Clause
 * Copyright (c) 2026 MNE-CPP Authors
 *
 * @file     test_inv_rap_music_truth.cpp
 * @author   Christoph Dinh <christoph.dinh@mne-cpp.org>
 * @since    2.4.0
 * @date     October 2026
 * @brief    Checks RAP-MUSIC and PWL-RAP-MUSIC against a known synthetic ground truth.
 *
 * MNE-CPP's RAP-MUSIC searches correlated dipole pairs (Mosher & Leahy 1999,
 * Dinh et al. 2012), for which mne-python has no counterpart. The oracle is
 * the forward model itself: noise-free data generated by known dipole pairs
 * lie exactly in their signal subspace, so the scan must return those pairs
 * with subspace correlation 1 and the generating orientations, and stop
 * once the remaining correlation falls below the threshold.
 */

//=============================================================================================================
// INCLUDES
//=============================================================================================================

#include <inv/rap_music/inv_rap_music.h>
#include <inv/rap_music/inv_pwl_rap_music.h>
#include <inv/rap_music/inv_dipole.h>
#include <mne/mne_forward_solution.h>
#include <mne/mne_source_space.h>
#include <fiff/fiff_evoked.h>
#include <fiff/fiff_named_matrix.h>

#include <cmath>

//=============================================================================================================
// QT INCLUDES
//=============================================================================================================

#include <QtTest>

//=============================================================================================================
// EIGEN INCLUDES
//=============================================================================================================

#include <Eigen/Core>

//=============================================================================================================
// USED NAMESPACES
//=============================================================================================================

using namespace INVLIB;
using namespace MNELIB;
using namespace FIFFLIB;
using namespace Eigen;

namespace
{

constexpr int kChannels = 40;
constexpr int kSources = 12;
constexpr int kSamples = 60;

// Deterministic, well-conditioned leadfield: every 3-column source block is distinct.
MatrixXd makeLeadField()
{
    MatrixXd G(kChannels, 3 * kSources);
    for (int i = 0; i < kChannels; ++i) {
        for (int j = 0; j < 3 * kSources; ++j) {
            G(i, j) = std::sin(0.31 * (i + 1) * (j + 2)) + 0.4 * std::cos(0.17 * i * i + 0.9 * j);
        }
    }
    return G;
}

MNEForwardSolution makeForward(const MatrixXd& G)
{
    MNEForwardSolution fwd;
    fwd.sol->data = G;
    fwd.sol->nrow = static_cast<int>(G.rows());
    fwd.sol->ncol = static_cast<int>(G.cols());
    fwd.nsource = kSources;
    return fwd;
}

// Data from one correlated pair per entry; pairs get independent time courses.
MatrixXd makeData(const MatrixXd& G, const QList<QPair<int, int>>& pairs, const QList<Matrix<double, 6, 1>>& ori)
{
    MatrixXd data = MatrixXd::Zero(kChannels, kSamples);
    for (int p = 0; p < pairs.size(); ++p) {
        MatrixXd Gp(kChannels, 6);
        Gp << G.middleCols(3 * pairs[p].first, 3), G.middleCols(3 * pairs[p].second, 3);
        const VectorXd topo = Gp * ori[p];
        for (int t = 0; t < kSamples; ++t) {
            data.col(t) += topo * std::sin(0.21 * (p + 1) * t + 0.7 * p);
        }
    }
    return data;
}

} // namespace

//=============================================================================================================
/**
 * DECLARE CLASS TestInvRapMusicTruth
 *
 * @brief Checks RAP-MUSIC against a synthetic ground truth.
 */
class TestInvRapMusicTruth : public QObject
{
    Q_OBJECT

private slots:
    void recoversPairs_data();
    void recoversPairs();
    void stopsAtThreshold();
    void rejectsInvalidInput();
    void evokedEstimate();
};

//=============================================================================================================
// DEFINE METHODS
//=============================================================================================================

void TestInvRapMusicTruth::recoversPairs_data()
{
    QTest::addColumn<bool>("powell");
    QTest::newRow("RAP-MUSIC") << false;
    QTest::newRow("PWL-RAP-MUSIC") << true;
}

//=============================================================================================================

void TestInvRapMusicTruth::recoversPairs()
{
    QFETCH(bool, powell);

    const MatrixXd G = makeLeadField();
    MNEForwardSolution fwd = makeForward(G);

    Matrix<double, 6, 1> o1, o2;
    o1 << 1.0, 0.2, -0.3, 0.0, 0.8, 0.5;
    o2 << -0.4, 0.9, 0.1, 0.6, 0.0, -0.7;
    const QList<QPair<int, int>> truth{{2, 9}, {4, 7}};
    const MatrixXd data = makeData(G, truth, {o1, o2});

    QList<InvDipolePair<double>> found;
    if (powell) {
        InvPwlRapMusic rap(fwd, false, 2, 0.5);
        rap.calculateInverse(data, found);
    } else {
        InvRapMusic rap(fwd, false, 2, 0.5);
        rap.calculateInverse(data, found);
    }

    QCOMPARE(found.size(), 2);
    for (int k = 0; k < 2; ++k) {
        const InvDipolePair<double>& d = found[k];
        const QPair<int, int> got = qMakePair(std::min(d.m_iIdx1, d.m_iIdx2), std::max(d.m_iIdx1, d.m_iIdx2));
        QVERIFY2(truth.contains(got), qPrintable(QString("pair %1 found (%2, %3)").arg(k).arg(got.first).arg(got.second)));

        // Noise-free data lie in the pair's subspace: correlation 1 up to SVD round-off.
        QVERIFY2(std::fabs(d.m_vCorrelation - 1.0) < 1e-6, qPrintable(QString("correlation %1").arg(d.m_vCorrelation, 0, 'g', 17)));

        // The orientation is the generating one up to sign and scale.
        const Matrix<double, 6, 1>& o = truth.indexOf(got) == 0 ? o1 : o2;
        Matrix<double, 6, 1> phi;
        if (d.m_iIdx1 == got.first) {
            phi << d.m_Dipole1.phi_x(), d.m_Dipole1.phi_y(), d.m_Dipole1.phi_z(), d.m_Dipole2.phi_x(), d.m_Dipole2.phi_y(), d.m_Dipole2.phi_z();
        } else {
            phi << d.m_Dipole2.phi_x(), d.m_Dipole2.phi_y(), d.m_Dipole2.phi_z(), d.m_Dipole1.phi_x(), d.m_Dipole1.phi_y(), d.m_Dipole1.phi_z();
        }
        const double cosine = std::fabs(phi.normalized().dot(o.normalized()));
        QVERIFY2(cosine > 1.0 - 1e-6, qPrintable(QString("orientation cosine %1").arg(cosine, 0, 'g', 17)));
    }
    QVERIFY(qMakePair(std::min(found[0].m_iIdx1, found[0].m_iIdx2), std::max(found[0].m_iIdx1, found[0].m_iIdx2)) != qMakePair(std::min(found[1].m_iIdx1, found[1].m_iIdx2), std::max(found[1].m_iIdx1, found[1].m_iIdx2)));
}

//=============================================================================================================

void TestInvRapMusicTruth::stopsAtThreshold()
{
    // One pair of sources, three iterations requested: after the true pair the
    // remaining correlation is below 0.99, so the scan must stop after the
    // second, sub-threshold pair is recorded.
    const MatrixXd G = makeLeadField();
    MNEForwardSolution fwd = makeForward(G);
    Matrix<double, 6, 1> o;
    o << 0.5, -0.5, 0.2, 0.7, 0.1, -0.3;
    MatrixXd data = makeData(G, {{1, 10}}, {o});
    // A second, weaker component outside every pair subspace, so the rank exceeds one.
    for (int t = 0; t < kSamples; ++t) {
        data.col(t) += 1e-3 * VectorXd::NullaryExpr(kChannels, [t](Index i) { return std::cos(1.7 * i + 0.3 * t); });
    }

    InvRapMusic rap(fwd, false, 3, 0.99);
    QList<InvDipolePair<double>> found;
    rap.calculateInverse(data, found);

    QVERIFY(found.size() >= 1);
    QVERIFY(found.size() < 3);
    QVERIFY(found.first().m_vCorrelation > 0.99);
    QCOMPARE(std::min(found.first().m_iIdx1, found.first().m_iIdx2), 1);
    QCOMPARE(std::max(found.first().m_iIdx1, found.first().m_iIdx2), 10);
    if (found.size() == 2) {
        QVERIFY(found.last().m_vCorrelation < 0.99);
    }
}

//=============================================================================================================

void TestInvRapMusicTruth::rejectsInvalidInput()
{
    const MatrixXd G = makeLeadField();
    QList<InvDipolePair<double>> found;

    InvRapMusic uninitialised;
    QVERIFY_THROWS_EXCEPTION(std::logic_error, uninitialised.calculateInverse(MatrixXd::Zero(kChannels, kSamples), found));

    MNEForwardSolution fwd = makeForward(G);
    InvRapMusic rap(fwd, false, 2, 0.5);
    QVERIFY_THROWS_EXCEPTION(std::invalid_argument, rap.calculateInverse(MatrixXd::Zero(kChannels - 1, kSamples), found));

    // A leadfield whose columns are not a multiple of three has no dipole grid.
    MNEForwardSolution bad = makeForward(G.leftCols(3 * kSources - 1));
    InvRapMusic badRap;
    QVERIFY(!badRap.init(bad, false, 2, 0.5));
}

//=============================================================================================================

void TestInvRapMusicTruth::evokedEstimate()
{
    // One pair, two requested: the data have rank one, so only the pair is returned.
    // Its rows carry |phi_k| * correlation, i.e. the split of the generating 6-vector.
    MNEForwardSolution fwd = makeForward(makeLeadField());
    for (int h = 0; h < 2; ++h) {
        MNESourceSpace hemi;
        hemi.vertno = VectorXi::LinSpaced(kSources / 2, 0, 10 * (kSources / 2 - 1)).array() + h;
        fwd.src.append(hemi);
    }
    Matrix<double, 6, 1> o;
    o << 1.0, 0.2, -0.3, 0.0, 0.8, 0.5;
    FiffEvoked evoked;
    evoked.data = makeData(makeLeadField(), {{2, 9}}, {o});
    evoked.times = RowVectorXf::LinSpaced(kSamples, 0.1f, 0.1f + 0.01f * (kSamples - 1));

    InvRapMusic rap(fwd, false, 2, 0.5);
    const InvSourceEstimate whole = rap.calculateInverse(evoked);
    QCOMPARE(static_cast<int>(whole.data.rows()), kSources);
    QCOMPARE(static_cast<int>(whole.data.cols()), kSamples);
    QCOMPARE(whole.vertices.size(), static_cast<Index>(kSources));
    QCOMPARE(whole.vertices[kSources / 2], 1);
    QCOMPARE(whole.tmin, 0.1f);
    QVERIFY(std::fabs(whole.tstep - 0.01f) < 1e-6f);

    const double norm1 = o.head<3>().norm() / o.norm();
    const double norm2 = o.tail<3>().norm() / o.norm();
    for (int s = 0; s < kSources; ++s) {
        const double expected = s == 2 ? norm1 : (s == 9 ? norm2 : 0.0);
        QVERIFY2((whole.data.row(s).array() - expected).abs().maxCoeff() < 1e-6,
                 qPrintable(QString("source %1: %2, expected %3").arg(s).arg(whole.data(s, 0), 0, 'g', 12).arg(expected)));
    }
    QCOMPARE(rap.calculateInverse(evoked.data, 0.1f, 0.01f).data, whole.data);

    // Sliding windows over stationary data give the same estimate in every window.
    rap.setStcAttr(20, 0.5f);
    const InvSourceEstimate windowed = rap.calculateInverse(evoked);
    QCOMPARE(static_cast<int>(windowed.data.cols()), kSamples);
    QVERIFY((windowed.data - whole.data).cwiseAbs().maxCoeff() < 1e-9);

    evoked.data.conservativeResize(kChannels - 1, NoChange);
    QVERIFY(rap.calculateInverse(evoked).isEmpty());
}

//=============================================================================================================
// MAIN
//=============================================================================================================

QTEST_GUILESS_MAIN(TestInvRapMusicTruth)
#include "test_inv_rap_music_truth.moc"
