#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 MNE-CPP Authors
#   Christoph Dinh <christoph.dinh@mne-cpp.org>

#
# @since    2.4.0
# @date     October, 2026
#
#
# @brief    Render the website quality page from the committed v2.4.0 quality JSON (T4.3).
"""Render ``doc/website/docs/development/quality.mdx`` from the quality JSON.

Every number on the page is read from ``doc/release/v2.4.0/*.json`` (the files
``generate_quality_report.py`` keeps current), so the page cannot drift from the
dashboard.  ``--check`` fails when the committed page differs from a fresh
render.

Usage
-----
    python3 tools/quality/render_quality_pages.py          # write the page
    python3 tools/quality/render_quality_pages.py --check  # CI: fail if stale
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
RELEASE_DIR = REPO_ROOT / "doc" / "release" / "v2.4.0"
PAGE = REPO_ROOT / "doc" / "website" / "docs" / "development" / "quality.mdx"


def _load(name: str) -> dict:
    return json.loads((RELEASE_DIR / name).read_text(encoding="utf-8"))


def _pct(value: float | None) -> str:
    return "—" if value is None else f"{value:.1f}%"


def _ratio(part: int, whole: int) -> str:
    return "—" if not whole else f"{part} / {whole} ({100.0 * part / whole:.0f}%)"


def library_rows(coverage: dict, api: dict, tests: dict, registry: dict) -> list[dict]:
    """One row per library under src/libraries, joined across the quality reports."""
    module_of_class = {c["name"]: c["module"] for c in registry.get("classes", [])}
    tests_per_lib: dict[str, int] = defaultdict(int)
    for test in tests.get("tests", []):
        for lib in {module_of_class.get(name) for name in test.get("registry_classes", [])} - {None}:
            tests_per_lib[lib] += 1

    rows = []
    for component, totals in sorted(coverage.get("components", {}).items()):
        scope, _, lib = component.partition("/")[2].partition("/")
        if scope != "libraries":
            continue
        evidence = api.get("by_library", {}).get(lib, {})
        rows.append({
            "library": lib,
            "line": totals.get("line_percent"),
            "branch": totals.get("branch_percent"),
            "tests": tests_per_lib.get(lib, 0),
            "examples": (evidence.get("eligible_with_registry_example", 0), evidence.get("eligible", 0)),
        })
    return rows


def render(coverage: dict, api: dict, tests: dict, parity: dict, dashboard: dict, registry: dict) -> str:
    g2 = dashboard["gates"]["G2_coverage"]
    g3 = dashboard["gates"]["G3_api_documentation"]
    thresholds = dashboard["thresholds"]
    lines = [
        "---",
        "id: quality",
        'title: "Quality Dashboard"',
        "sidebar_label: Quality Dashboard",
        "---",
        "",
        "{/* Generated by tools/quality/render_quality_pages.py from doc/release/v2.4.0/*.json. Do not edit. */}",
        "",
        "# Quality Dashboard",
        "",
        "Release-gate status for v2.4.0, generated from the committed quality reports in",
        "[`doc/release/v2.4.0`](https://github.com/mne-tools/mne-cpp/tree/staging/doc/release/v2.4.0).",
        f"Coverage is measured on commit `{(coverage['source'].get('commit') or 'unknown')[:9]}`.",
        "",
        "## Release gates",
        "",
        "| Gate | Target | Current |",
        "|---|---|---|",
        f"| Combined line coverage | {thresholds['coverage_line_combined']:.0f}% | {_pct(g2['line_combined'])} |",
        f"| Library line coverage | {thresholds['coverage_line_libraries']:.0f}% | {_pct(g2['line_libraries'])} |",
        f"| Library branch coverage | {thresholds['coverage_branch_libraries']:.0f}% | {_pct(g2.get('branch_libraries'))} |",
        f"| Application line coverage | {thresholds['coverage_line_applications']:.0f}% | {_pct(g2['line_applications'])} |",
        f"| Tool line coverage | {thresholds['coverage_line_tools']:.0f}% | {_pct(g2['line_tools'])} |",
        f"| Eligible APIs with an executable example | {thresholds['example_eligible_backed']:.0f}% "
        f"| {_pct(g3['eligible_backed_percent'])} of {g3['example_eligible']} |",
        "",
        "## Libraries",
        "",
        "Coverage per library, tests that exercise a registered class, and registered examples",
        "among example-eligible APIs.",
        "",
        "| Library | Line | Branch | Tests | Examples |",
        "|---|---:|---:|---:|---:|",
    ]
    for row in library_rows(coverage, api, tests, registry):
        lines.append(f"| `{row['library']}` | {_pct(row['line'])} | {_pct(row['branch'])} | {row['tests']} "
                     f"| {_ratio(*row['examples'])} |")
    evidence = parity["summary"]["by_evidence"]
    lines += [
        "",
        "## MNE-Python parity evidence",
        "",
        f"{parity['summary']['claims']} parity claims, by the strongest evidence behind each:",
        "",
        "| Evidence | Claims |",
        "|---|---:|",
    ]
    lines += [f"| {level} | {count} |" for level, count in evidence.items()]
    lines.append("")
    return "\n".join(lines)


def build(repo_root: Path = REPO_ROOT) -> str:
    release = repo_root / "doc" / "release" / "v2.4.0"

    def load(name: str) -> dict:
        return json.loads((release / name).read_text(encoding="utf-8"))

    registry = json.loads((repo_root / "doc" / "api_registry.json").read_text(encoding="utf-8"))
    return render(load("coverage-baseline.json"), load("api-evidence-baseline.json"), load("test-inventory.json"),
                  load("parity-baseline.json"), load("quality-baseline.json"), registry)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if the committed page is stale")
    args = parser.parse_args(argv)
    page = build()
    if args.check:
        if not PAGE.is_file() or PAGE.read_text(encoding="utf-8") != page:
            print(f"FAIL: {PAGE.relative_to(REPO_ROOT)} is stale; run tools/quality/render_quality_pages.py")
            return 1
        print(f"PASS: {PAGE.relative_to(REPO_ROOT)} matches the quality JSON.")
        return 0
    PAGE.write_text(page, encoding="utf-8")
    print(f"wrote {PAGE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
