//=============================================================================================================
/**
 * SPDX-License-Identifier: BSD-3-Clause
 * Copyright (c) 2026 MNE-CPP Authors
 *   Christoph Dinh <christoph.dinh@mne-cpp.org>
 *
 * @file standard_montage.h
 * @since May 2026
 * @brief Built-in 10-20 / 10-10 / 10-05 EEG electrode position tables in MNI head coordinates.
 *
 * @ref UTILSLIB::StandardMontage provides hard-coded, vendor-
 * neutral electrode placements for the three canonical
 * extended international electrode systems. Returning the
 * coordinates in MNI head metres (origin between LPA and RPA,
 * +x toward NAS, +y toward LPA, +z up) lets every consumer in
 * mne-cpp — the Polhemus coregistration wizard, the topographic
 * layout maker, the forward modelling pre-processor — fall
 * back to a default cap when the user has no digitised
 * positions of their own.
 *
 * The 10-05 system is generated by densifying the explicit
 * 10-10 table so the larger system stays consistent with the
 * smaller one. All lookups are O(N) over the requested
 * system and the tables are constructed lazily on first use,
 * which keeps the static initialisation cost out of every
 * binary that merely links against UTILSLIB.
 */

#ifndef STANDARD_MONTAGE_H
#define STANDARD_MONTAGE_H

//=============================================================================================================
// INCLUDES
//=============================================================================================================

#include "../utils_global.h"

//=============================================================================================================
// EIGEN INCLUDES
//=============================================================================================================

#include <Eigen/Core>

//=============================================================================================================
// QT INCLUDES
//=============================================================================================================

#include <QStringList>
#include <QMap>

//=============================================================================================================
// DEFINE NAMESPACE UTILSLIB
//=============================================================================================================

namespace UTILSLIB
{

//=============================================================================================================
/**
 * @brief Represents an electrode position in a montage.
 */
struct UTILSSHARED_EXPORT ElectrodePosition
{
    QString name;              /**< Electrode name (e.g. "Cz", "Fp1"). */
    Eigen::Vector3d pos;       /**< Position in metres (MNI head coords). */
};

//=============================================================================================================
/**
 * @brief Standard EEG montage with named electrode positions.
 */
class UTILSSHARED_EXPORT StandardMontage
{
public:
    //=========================================================================================================
    /**
     * @brief Supported standard montage systems.
     */
    enum class System {
        Standard_1020,    /**< 10-20 system (21 electrodes). */
        Standard_1010,    /**< 10-10 system (81 electrodes). */
        Standard_1005     /**< 10-05 system (345 electrodes). */
    };

    //=========================================================================================================
    /**
     * @brief Get a standard montage by system name.
     *
     * @param[in] system  The montage system.
     *
     * @return List of electrode positions.
     */
    static QList<ElectrodePosition> getMontage(System system);

    //=========================================================================================================
    /**
     * @brief Get electrode names for a standard montage.
     *
     * @param[in] system  The montage system.
     *
     * @return List of electrode names.
     */
    static QStringList getElectrodeNames(System system);

    //=========================================================================================================
    /**
     * @brief Look up a single electrode position by name.
     *
     * Searches through all built-in montages.
     *
     * @param[in] name  Electrode name (case-insensitive).
     * @param[out] pos  Position if found.
     *
     * @return true if found.
     */
    static bool findElectrode(const QString& name, Eigen::Vector3d& pos);

    //=========================================================================================================
    /**
     * @brief Get the number of electrodes in a montage.
     */
    static int electrodeCount(System system);

private:
    static QList<ElectrodePosition> buildStandard1020();
    static QList<ElectrodePosition> buildStandard1010();
};

} // namespace UTILSLIB

#endif // STANDARD_MONTAGE_H
