name: Documentation

on:
  push:
    branches:
    - master
    - github_actions

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt Dev Tools, Doxygen and Graphviz
      run: |
        sudo apt-get install -qq qttools5-dev-tools doxygen graphviz
    - name: Run Doxygen
      run: |        
        cd doc
        doxygen mne-cpp_doxyfile
        tar cfvz docu_doxygen.tar.gz /html     
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: docu_doxygen.tar.gz
        path: .