name: Linux

on:
  push:
    branches:
    - master
    - github_actions

jobs:
  Release:
    runs-on: ubuntu-16.04
    
    steps:
    - name: Clone repository
      uses: actions/checkout@v1  
    - name: Install hub
      uses: geertvdc/setup-hub@master
    - name: Install Qt
      run: |
        sudo apt-get install build-essential libgl1-mesa-dev -y
        pip3 install setuptools wheel
        pip3 install aqtinstall --pre
        python3 -m aqt install --outputdir $HOME/Qt 5.10.1 linux desktop --module qtcharts
        echo "::add-path::$HOME/Qt/5.10.1/gcc_64/bin"
    - name: Configure and compile MNE-CPP
      run: |        
        qmake -r MNECPP_CONFIG+=noTests
        make -j2 
    - name: Package binaries
      run: |
        # Downloading linuxdeployqt from continious release
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        sudo chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        #creating a directory for linuxdeployqt to create results 
        sudo mkdir -p -m777 mne-cpp
        # Install non-QT packages, just paranoia.
        #sudo apt-get install -qq libicu52 libxcb-xinerama0
        #setting linuxdeployqt to variable
        linuxdeployqt=linuxdeployqt-continuous-x86_64.AppImage
        #archive file name created
        archive_name="mne-cpp-linux-x86_64-dev-build.tar.gz"
        #copying built data to folder for easy packaging 	
        cp -r ./bin ./lib mne-cpp/
        #dropping into folder to easily package all results from linuxdeployqt
        cd mne-cpp
        #linuxdeployqt uses mne_scan binary to resolve dependencies in current directory. 
        ../$linuxdeployqt bin/mne_scan -verbose2
        #creating archive of everything in current directory
        tar cfvz ../$archive_name ./*   
    - name: Setup Github credentials
      uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}      
    - name: Update dev_build_linux tag and release
      env:
        GITHUB_USER: LorenzE
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email lorenzesch@hotmail.com
        git config --global user.name $GITHUB_USER
        # Delete current tag locally if existent
        if [ $(git tag -l "dev_build_linux") ]; then
          git tag -d dev_build_linux
        fi
        # Delete current release remotley. This gets rid of the left over draft release. This must be done before deleting the remote tag
        #if [ $(hub release show -f %t dev_build_linux) == "dev_build_linux" ]; then
        hub release delete dev_build_linux
        #fi        
        # Delete current tag remotley
        git push origin :refs/tags/dev_build_linux
        # Create new tag once again
        git tag -a dev_build_linux -m "Dev Build Linux"
        # Send the new tag
        git push --force origin refs/tags/dev_build_linux:refs/tags/dev_build_linux
    - name: Deploy binaries with dev_build_linux release at Github
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mne-cpp-linux-x86_64-dev-build.tar.gz
        asset_name: mne-cpp-linux-x86_64-dev-build.tar.gz
        tag: dev_build_linux

  Documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Install Qt Dev Tools, Doxygen and Graphviz
      run: |
        sudo apt-get install -qq qttools5-dev-tools doxygen graphviz
    - name: Run Doxygen and package result
      run: |        
        cd doc
        doxygen mne-cpp_doxyfile
        tar cfvz docu_doxygen.tar.gz html
    - name: Upload artifact to Github actions log screen
      uses: actions/upload-artifact@v1
      with:
        name: docu_doxygen.tar.gz
        path: .
    # - name: Setup Github credentials
    #   uses: fusion-engineering/setup-git-credentials@v2
    #   with:
    #     credentials: ${{secrets.GIT_CREDENTIALS}}
    # - name: Update documentation at Github pages
    #   run: |
    #     git clone -b gh-pages --single-branch --no-checkout --depth 1 https://github.com/mne-tools/mne-cpp gh-pages
    #     cd gh-pages

    #     # Remove all files first
    #     git rm * -r
    #     git commit --amend -a -m 'Update docu'

    #     touch .nojekyll
        
    #     cp -r ../html/* .

    #     git add *
    #     git add .nojekyll
    #     git commit --amend -a -m 'Update docu'
    #     git push -f --all