name: Linux

on:
  push:
    branches:
    - master
    - github_actions

jobs:
  Release:
    runs-on: ubuntu-16.04
    
    steps:
    - name: Clone repository
      uses: actions/checkout@v1  
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.10.1
        modules: qtcharts
    - name: Configure and compile MNE-CPP
      run: |        
        qmake -r MNECPP_CONFIG+=noTests
        make -j2 
    - name: Package binaries
      run: |
        # Downloading linuxdeployqt from continious release
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        sudo chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        # Creating a directory for linuxdeployqt to create results 
        sudo mkdir -p -m777 mne-cpp
        # Copying built data to folder for easy packaging 	
        cp -r ./bin ./lib mne-cpp/
        # linuxdeployqt uses mne_scan binary to resolve dependencies in current directory. 
        cd mne-cpp
        ../linuxdeployqt-continuous-x86_64.AppImage bin/mne_scan -verbose2
        # creating archive of everything in current directory
        tar cfvz ../mne-cpp-linux-x86_64-dev-build.tar.gz ./*   
    - name: Setup Github credentials
      uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}      
    - name: Update dev_build_linux tag and release
      run: |
        git config --global user.email lorenzesch@hotmail.com
        git config --global user.name LorenzE
        git tag dev_build -f -a -m "Development Builds"
        git push -f --tag
    - name: Deploy binaries with dev_build release at Github
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mne-cpp-linux-x86_64-dev-build.tar.gz
        asset_name: mne-cpp-linux-x86_64-dev-build
        tag: dev_build
        overwrite: true

  Documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Install Qt Dev Tools, Doxygen and Graphviz
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq qttools5-dev-tools doxygen graphviz
    - name: Run Doxygen and package result
      run: |        
        cd doc
        doxygen mne-cpp_doxyfile
        tar cfvz docu_doxygen.tar.gz html
    - name: Setup Github credentials
      uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}
    - name: Update documentation at Github pages
      run: |    
        cd doc
        git config --global user.email lorenzesch@hotmail.com
        git config --global user.name LorenzE
        git clone -b gh-pages --single-branch --no-checkout --depth 1 https://github.com/mne-tools/mne-cpp gh-pages
        cd gh-pages
        # Remove all files first
        git rm * -r
        git commit --amend -a -m 'Update docu'
        touch .nojekyll        
        # Copy doxygen files
        cp -r ../html/* .
        # Add all new files, commit and push
        git add *
        git add .nojekyll
        git commit --amend -a -m 'Update docu'
        git push -f --all        
    - name: Deploy qch docu data base with dev_build release at Github
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: doc/qt-creator_doc/mne-cpp.qch
        asset_name: mne-cpp-doc-qtcreator
        tag: dev_build