name: MacOS

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - github_actions

jobs:
  Release:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install 7Zip
      run: brew install p7zip
    - name: Install Qt
      run: |
        pip3 install setuptools wheel
        pip3 install aqtinstall --pre
        python3 -m aqt install --outputdir $HOME/Qt 5.10.1 mac desktop --module qtcharts
        echo "::add-path::$HOME/Qt/5.10.1/clang_64/bin"
    - name: Configure and compile MNE-CPP
      run: |        
        qmake -r MNECPP_CONFIG+=noTests
        make -j2