name: MacOS

on:
  push:
    branches:
    - master
    - github_actions
    
jobs:
  Release:
    runs-on: macos-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Install hub
      run: |
        tar --help
        wget https://github.com/github/hub/releases/download/v2.13.0/hub-darwin-amd64-2.13.0.tgz
        ls -l
        tar xzvf hub-darwin-amd64-2.13.0.tgz $HOME/
        ls -l
        cd $HOME/hub
        ls -l
        echo "::add-path::$HOME/hub"
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.10.1
        modules: qtcharts
    - name: Configure and compile MNE-CPP
      run: |        
        qmake -r MNECPP_CONFIG+=noTests MNECPP_CONFIG+=noExamples
        make -j2
    - name: Setup Github credentials
      uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}  
    - name: Update dev_build_mac tag and release
      env:
        GITHUB_USER: LorenzE
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email lorenzesch@hotmail.com
        git config --global user.name $GITHUB_USER
        # Delete current tag locally if existent
        if [ $(git tag -l "dev_build_mac") ]; then
          git tag -d dev_build_mac
        fi
        # Delete current release remotley. This gets rid of the left over draft release. This must be done before deleting the remote tag
        #if [ $(hub release show -f %t dev_build_mac) == "dev_build_mac" ]; then
        hub release delete dev_build_mac
        #fi        
        # Delete current tag remotley
        git push origin :refs/tags/dev_build_mac
        # Create new tag once again
        git tag -a dev_build_mac -m "Dev Build MacOS"
        # Send the new tag
        git push --force origin refs/tags/dev_build_mac:refs/tags/dev_build_mac
    - name: Deploy MNE Scan binaries with dev_build_mac release at Github
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/mne_scan.dmg
        asset_name: mne_scan.dmg
        tag: dev_build_mac
    - name: Deploy MNE Browse binaries with dev_build_mac release at Github
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/mne_browse.dmg
        asset_name: mne_browse.dmg
        tag: dev_build_mac
    - name: Deploy MNE Analyze binaries with dev_build_mac release at Github
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/mne_analyze.dmg
        asset_name: mne_analyze.dmg
        tag: dev_build_mac