name: MacOS

on:
  push:
    branches:
    - master
    - github_actions
    
jobs:
  Release:
    runs-on: macos-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.10.1
        modules: qtcharts
    - name: Configure and compile MNE-CPP
      run: |        
        echo $PATH
        qmake -r MNECPP_CONFIG+=noTests MNECPP_CONFIG+=noExamples
        make -j2
    - name: Setup Github credentials
      uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}  
    - name: Update dev_build_mac tag and release
      run: |
        git config --global user.email lorenzesch@hotmail.com
        git config --global user.name LorenzE
        git tag dev_build -f -a -m "Development Builds"
        git push -f --tag        
    - name: Deploy MNE Scan binaries with dev_build release at Github
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/mne_scan.dmg
        asset_name: mne_scan_mac
        tag: dev_build
        overwrite: true
    - name: Deploy MNE Browse binaries with dev_build release at Github
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/mne_browse.dmg
        asset_name: mne_browse_mac
        tag: dev_build
        overwrite: true
    - name: Deploy MNE Analyze binaries with dev_build release at Github
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/mne_analyze.dmg
        asset_name: mne_analyze_mac
        tag: dev_build
        overwrite: true