name: Test MD to PDF

on:
  push:
    branches:
      - pdf
jobs:
  Conversion:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Convert pdfs
      uses: BaileyJM02/markdown-to-pdf@v1.0.1
      with:
        input_dir: doc/gh-pages/pages/development
        output_dir: pdf
        build_html: false
    - name: Upload PDFs
      uses: actions/upload-artifact@v2
      with:
        name: PDFs
        path: pdf/

    # - name: Upload file data
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Files
    #     path: filelist.dat
